### ISSUE TITLE
EHR Management Tasks [EPIC]

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#718]
- [ ] Add support for merging EHRs - creates a new merge EHR, links merged EHRs together, allows resolving the merged EHR by the merged EHR UIDs.
- [ ] Add support for disabling queerying and modifiabilty of the EHR - EHR_STATUS management.
- [ ] Add support for logical deletion of an EHR
- [ ] Add support for physical deletion of an EHR
- [ ] Add support for EHR import and export
