### ISSUE TITLE
Template management features [EPIC]

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver#779]
- [ ] OPT identification https://github.com/ppazos/cabolabs-ehrserver/issues/775
- [x] OPT multi tenancy https://github.com/ppazos/cabolabs-ehrserver/issues/764
- [x] OPT upload store user and organization that uploaded the OPT https://github.com/ppazos/cabolabs-ehrserver/issues/777
- [x] OPT internal versioning https://github.com/ppazos/cabolabs-ehrserver/issues/776
- [x] OPT change isPublic to shareWithAllOrganizations https://github.com/ppazos/cabolabs-ehrserver/issues/778

**Comment by ppazos** [comment]
OPT identification needs input from the openEHR SEC, will close this EPIC and handle the identification part separately
